name: Reusable workflow to run smoke tests on different k8s versions

on:
  workflow_call:

jobs:
  smoke-tests:
    name: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetesVersion: [v1.33, v1.32, v1.31]
        include:
          - kubernetesVersion: v1.33
            kindImage: kindest/node:v1.33.1@sha256:14ffd6ee8a3daa20cc934ba786626b181e1797268c5465f2c299a7cf54494c77
          - kubernetesVersion: v1.32
            kindImage: kindest/node:v1.32.0@sha256:c48c62eac5da28cdadcf560d1d8616cfa6783b58f0d94cf63ad1bf49600cb027
          - kubernetesVersion: v1.31
            kindImage: kindest/node:v1.31.4@sha256:2cb39f7295fe7eafee0842b1052a599a4fb0f8bcf3f83d96c7f4864c357c6c30
    uses: kedacore/keda/.github/workflows/template-smoke-tests.yml@main
    with:
      runs-on: ubuntu-latest
      kubernetesVersion: ${{ matrix.kubernetesVersion }}
      kindImage: ${{ matrix.kindImage }}
